// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWkikg1VT3a1UskBzCQj5Hlj4k99uugpg',
    appId: '1:122693931123:web:fde60418fcbe7a2f685a06',
    messagingSenderId: '122693931123',
    projectId: 'human-firewall-bfdcb',
    authDomain: 'human-firewall-bfdcb.firebaseapp.com',
    storageBucket: 'human-firewall-bfdcb.firebasestorage.app',
    measurementId: 'G-XMVY18HXXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJGHZaiHqE1qCwyD5BOvnTIa51Yxc0R50',
    appId: '1:122693931123:android:6409c708fb256d35685a06',
    messagingSenderId: '122693931123',
    projectId: 'human-firewall-bfdcb',
    storageBucket: 'human-firewall-bfdcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hRFWKf7_OSNR3iMY43_l5FkD-yuussE',
    appId: '1:122693931123:ios:9166df249c949ece685a06',
    messagingSenderId: '122693931123',
    projectId: 'human-firewall-bfdcb',
    storageBucket: 'human-firewall-bfdcb.firebasestorage.app',
    iosBundleId: 'com.example.humanFirewall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hRFWKf7_OSNR3iMY43_l5FkD-yuussE',
    appId: '1:122693931123:ios:9166df249c949ece685a06',
    messagingSenderId: '122693931123',
    projectId: 'human-firewall-bfdcb',
    storageBucket: 'human-firewall-bfdcb.firebasestorage.app',
    iosBundleId: 'com.example.humanFirewall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWkikg1VT3a1UskBzCQj5Hlj4k99uugpg',
    appId: '1:122693931123:web:088856fcaf6da076685a06',
    messagingSenderId: '122693931123',
    projectId: 'human-firewall-bfdcb',
    authDomain: 'human-firewall-bfdcb.firebaseapp.com',
    storageBucket: 'human-firewall-bfdcb.firebasestorage.app',
    measurementId: 'G-PRHE4KD24L',
  );
}
